AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
