AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - vendor/**/*
    - example/**/*

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rspec-sunspot-profiles.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
